Change to UTC time calculations to avoid DST messing things up
NREL/resstock pull request #528
Opened 2021-01-08 16:29 UTC by rajeee

Resolves the issue of timestamps being incorrect around the DST switchover time when using AMY weather files.

## Pull Request Description
Ruby resolves: `Time.new(2019,3,10,2,45,0)` into either `"2019-03-10 03:45:00 -0600"` or `"2019-03-10 02:45:00 -0700"` depending upon system timezone settings.  This fixes the issue by using utc timestamps for calculations so the local timezone settings doesn't interfere. 

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing
- [ ] The [changelog](https://github.com/NREL/resstock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with develop

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

2021-01-08 18:32 UTC, joseph-robertson reviewed
You confirmed this works on eagle?

2021-01-08 23:21 UTC, rajeee commented
@joseph-robertson  Yes, verified that it works in eagle. Also added test which would fail if not for this fix.

2021-01-08 23:22 UTC, rajeee commented
@lixiliu @afontani FYI

2021-01-11 15:18 UTC, joseph-robertson requested changes
I think just update the changelog, and this should be good to go.

2021-01-11 17:31 UTC, joseph-robertson approved these changes

2021-01-11 17:36 UTC, merged