City Boundaries
NREL/resstock pull request #874
Opened 2022-04-04 18:19 UTC by afontani

## Pull Request Description

**Purpose:** Adding City Boundaries as a housing characteristic in ResStock. This way users can aggregate directly by a given City.

### Infrastructure changes

**Git Large File Storage (LFS):** Repository now uses LFS for some of the housing characteristics. GitHub has a maximum files size of 100 MB. With the housing characteristic files getting larger, we now have a couple of housing characteristics that are larger than this threshold. 

The difference is that GitHub stores the file as a pointer, and stores the data in a database. These files are still version-controlled. 

Documentation: [https://git-lfs.github.com/](https://git-lfs.github.com/)

### Housing Characteristics Changes

### Options Lookup Changes

## Checklist

Not all may apply:

- [ ] Tests (and test files) have been updated
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected integration/regression test changes

2022-04-04 19:22 UTC, shorowit commented
I don't love the idea of requiring LFS. It strikes me that the reason these TSVS are so large is because 6 decimal places are required for every value. Aside from the fact that that it has always seemed excessively precise to me given the uncertainty on the values, these two large TSVs are essentially just 1s and 0s. Maybe it's time to remove the 6 decimal place requirement? For what it's worth, I changed from 6 decimal places to 0 decimal places on County.tsv and it dropped from 124mb to 28mb.

2022-04-04 19:46 UTC, afontani commented
@shorowit: Thanks. I think it is time. I can try to relax this requirement in the integrity checks and see how much it would save us.

2022-04-04 19:51 UTC, shorowit commented
@afontani Another option would be to create a separate file that defines the required number of decimal places on a per-TSV basis. So these new TSVs could use 0 while others could remain at 6.

2022-04-04 21:53 UTC, joseph-robertson commented
That approach might also be helpful for tracking which TSVs have actual distributions and which just provide mappings.

2022-04-05 22:49 UTC, afontani commented
@joseph-robertson, @shorowit: I think I will add a column to the `source_report` in resstock-estimation that states if the characteristic is a "mapping" characteristic or a "distribution" characteristic.

2022-04-13 19:16 UTC, ejhw reviewed
> The limiting factor was Burlington Vermont with about 16,000 dwelling units.
What does "limiting factor" mean?

2022-04-13 19:32 UTC, afontani commented on CHANGELOG.md
@ejhw: Thanks. Addressed [76337ee](https://github.com/NREL/resstock/pull/874/commits/76337eeb8d31fdbde0fb58ffe88782c88a0b7dba)

2022-04-18 20:57 UTC, ejhw requested changes
Thanks @afontani . Few comments/questions

- [x] - Cities.tsv --> City.tsv to be consistent with naming of other TSV files
- [x] ~~Why not use human readable strings for city/place, e.g., "Birmingham, AL" instead of "al_birmingham". I guess so it is in alphabetical order? I think "Birmingham, AL" would makes things easier because it would be readily interpretted by Tableau.~~
- [x] - ~~@Tony, we could make "County and PUMA" the string version, and leave PUMA and County as geo IDs? That would not mess up Sightglass but would let us have one field with human-useful information.~~ I retracted this suggestion; @afontani and I decided to revert the PUMA names to use PUMA ids instead 
- [x] - "# Assumption: The value 'In another census Place' designates the fraction of dwelling units in a Census Place with less total dwelling units than the threshold." "less" --> "fewer"
- [x] - What does "U.S. Census data as of July 1, 2015" mean if the census only happens every ten years?

2022-04-20 19:30 UTC, merged